---
name: Go Tests
on: 
    push:
    pull_request:

jobs:
    test:
        name: Go tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - uses: actions/setup-go@v5
            - run: cd ./src && make binaries
            - run: cd ./src && go test ./...
            - run: make test-impl cmd-parser-text=echo
            - run: make test_open_metrics_validator