---
name: Python Tests
on: 
    push:
    pull_request:

jobs:
    test:
        name: Python tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - uses: actions/setup-python@v5
            - run: make test_prometheus_client_python_parser